name: Build&TestApi

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test with coverage
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool
        export PATH="$PATH:/home/runner/.dotnet/tools"

        dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=TestResults/

        reportgenerator -reports:TestResults/coverage.cobertura.xml -targetdir:coveragereport -reporttypes:TextSummary > coverage-summary.txt

        cat coverage-summary.txt

        COVERAGE=$(grep "Line coverage" coverage-summary.txt | awk '{print $3}' | sed 's/%//')

        echo "Line coverage is $COVERAGE%"

        if (( $(echo "$COVERAGE < 80" | bc -l) )); then
          echo "Coverage below 80% ($COVERAGE%)"
          exit 1
        else
          echo "Coverage OK ($COVERAGE%)"
        fi
